version: "3.0"

services:
  mssql:
    container_name: josergdev-todoapp-csharp-mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
